version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toan123
    volumes:
      - ./mongodb-data:/home/ton/mongodb/data/db
    ports:
      - "27017:27017"
    # networks:
    #   - DE


networks: 
  default: 
    external: 
      name: hadoopspark
# networks:
#   DE:
#     driver: bridge
    
